add precondition validation to build
If a package requires particular users or groups to exist, or
specific system directories to be set up with specific
permissions to work, the options file can now have an
initial_checkup function that verifies them.

Also: fix a couple of stupid typos in the build script; and
modify add_package_user so it removes the mail spool file for
package users (who do not need one).

diff --git a/usr/lib/pkgusr/build b/usr/lib/pkgusr/build
--- a/usr/lib/pkgusr/build
+++ b/usr/lib/pkgusr/build
@@ -24,6 +24,8 @@
 # if any problems have occurred. If that is the case, use the corresponding
 # *.log files to see the error messages in context.
 
+initial_checkup || (echo "aborting!"; exit 1)
+
 function apply_patches()
 {
     PATCHDIR="${HOME}/patches"
@@ -61,13 +63,13 @@ then
         exit 1
     fi
     SOURCEDIR="${HOME}/src"
-    if [ -f "${SOURCEDIR}/*.lzma" ]
+    if [ -f ${SOURCEDIR}/*.lzma ]
     then
         lzma -d < ${SOURCEDIR}/*.lzma | tar xf -
     else
         tar xf ${SOURCEDIR}/*.tar*
     fi
-    cd "${USER}*" || exit 2
+    cd ${USER}* || exit 2
     if [ -d "${HOME}/patches" ]
     then
         apply_patches
