remove trailing whitespaces

diff --git a/usr/sbin/add_package_user b/usr/sbin/add_package_user
--- a/usr/sbin/add_package_user
+++ b/usr/sbin/add_package_user
@@ -6,7 +6,7 @@
 # Package user home directories will be located under this directory
 homebase=/usr/src
 
-# Contents of following directory are copied into home directory when creating 
+# Contents of following directory are copied into home directory when creating
 # a new package user (existing files will not be overwritten)
 skel=/etc/pkgusr/skel-package
 
@@ -39,7 +39,7 @@ passwd=/etc/passwd
 # are ONLY used by package users!  When adding new users and
 # groups, remember to specify the UID and GIDs.
 #
-# <minuid>(incl.) and <maxuid>(excl.) determine the numeric range 
+# <minuid>(incl.) and <maxuid>(excl.) determine the numeric range
 # from which the new account's UID will be picked in the following way:
 #
 #  1. If the range contains no unused UID => Exit with error.
@@ -66,21 +66,21 @@ if [ $UID -ne 0 ]; then echo Please run this script as root. ; exit 1; fi
 
 #test if user already exists
 grep "^$name:.*" $passwd
-if [ $? -eq 0 ]; then 
+if [ $? -eq 0 ]; then
   echo 'Package user already exists! Do su '$name' to do maintenance work.'
   exit 1
-fi 
+fi
 
 # validate minuid, maxuid, etc
 error=0
 
 if [ $minuid -ge $maxuid ]; then
-  echo 'Error: minuid must be less than maxuid !' 
+  echo 'Error: minuid must be less than maxuid !'
   exit 1
 fi
 
 if [ $mingid -ge $maxgid ]; then
-  echo 'Error: mingid must be less than maxgid !' 
+  echo 'Error: mingid must be less than maxgid !'
   exit 1
 fi
 
@@ -91,7 +91,7 @@ u=0
 for i in $uidlist
 do
   if [ $i -ge $maxuid ]; then break; fi
-  if [ $i -ge $minuid ]; then u=$i; fi 
+  if [ $i -ge $minuid ]; then u=$i; fi
 done
 
 #if no UID from the range is used, pick the first, otherwise pick the one
@@ -106,7 +106,7 @@ if [ $u -ge $maxuid ]; then
   do
     if [ $u -eq $i ]; then u=`expr $u + 1` ; fi
     if [ $i -ge $maxuid ]; then break; fi
-  done  
+  done
 
   if [ $u -ge $maxuid ]; then
     echo Error: UID range is full!
@@ -131,14 +131,14 @@ do
   oldg=$g #save gid from previous run
   createinstall=$creategroup
   creategroup=0
- 
+
   #test if group already exists and extract gid if so
   g=`grep ^${group}:.\* $grpfile | cut -d : -f 3 -`
 
   #if group does not exist, then check range for a free gid
-  if [ z$g = z ]; then 
+  if [ z$g = z ]; then
     creategroup=1
-    
+
     gidlist=`cut -d : -f 3 $grpfile | sort -n`
 
     #find last used GID within range
@@ -152,8 +152,8 @@ do
     #if no GID from the range is used, pick the first, otherwise pick the one
     #immediately following the last GID in use.
     if [ $g -eq 0 ]; then g=$mingid; else g=`expr $g + 1`; fi
-    
-    #don't reuse gid from previous run 
+
+    #don't reuse gid from previous run
     if [ $g -eq $oldg ]; then g=`expr $g + 1`; fi
 
     #if the GID determined above is >= maxgid (i.e. illegal)
@@ -165,7 +165,7 @@ do
         if [ $g -eq $i ]; then g=`expr $g + 1` ; fi
         if [ $g -eq $oldg ]; then g=`expr $g + 1` ; fi
         if [ $i -ge $maxgid ]; then break; fi
-      done  
+      done
 
       if [ $g -ge $maxgid ]; then
         echo Error: GID range is full!
@@ -190,7 +190,7 @@ if [ $creategroup -eq 1 ]; then
   fi
   echo Creating group $gname with gid $g
   groupadd -g $g $gname || exit 1
-else 
+else
   echo Group $gname has gid $g
 fi
 
